services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vol:/app/vol
      - ./backend/fixtures:/app/fixtures
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py init_data &&
                    daphne -b 0.0.0.0 -p ${PORT:-8000} catalogue_system.asgi:application"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-false}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  redis:
    depends_on:
      - app
    image: redis:5.0.3-alpine
    restart: unless-stopped
    expose:
      - "6379"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - app
      - redis
      - db
    restart: unless-stopped
    command: sh -c "python -m celery -A catalogue_system worker -B -l INFO --schedule /tmp/celery-schedule"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-false}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      CELERY_BROKER_URL: "redis://redis:6379/0"
      ANALYTICS_DATASET_ID: ${ANALYTICS_DATASET_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}