# Generated by Django 6.0.3 on 2026-04-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_mail_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_mail_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
