# Generated by Django 6.0.3 on 2026-04-13 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cocktail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymous_user_id", models.CharField(max_length=255)),
                (
                    "session_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session_end",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("browser", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("age_confirmation", "Age Confirmation"),
                            ("page_view", "Page View"),
                            ("search_query", "Search Query"),
                            ("filter_applied", "Filter Applied"),
                            ("filters_reset", "Filters Reset"),
                            ("cocktail_card_view", "Card View"),
                            ("cocktail_page_open", "Page Open"),
                            ("servings_changed", "Servings Changed"),
                            ("signup", "Signup"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("rating_added", "Rating Added"),
                            ("review_added", "Review Added"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("anonymous_user_id", models.CharField(max_length=255)),
                ("page_name", models.CharField(blank=True, max_length=255, null=True)),
                ("page_url", models.TextField(blank=True, null=True)),
                ("search_text", models.TextField(blank=True, null=True)),
                ("filters_applied", models.BooleanField(blank=True, null=True)),
                (
                    "filter_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "filter_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("previous_filters", models.TextField(blank=True, null=True)),
                ("results_count", models.PositiveIntegerField(blank=True, null=True)),
                ("servings_number", models.PositiveIntegerField(blank=True, null=True)),
                ("age_confirmed", models.BooleanField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("success", models.BooleanField(blank=True, null=True)),
                ("rating_value", models.PositiveIntegerField(blank=True, null=True)),
                ("review_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cocktail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cocktail.cocktail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.session",
                    ),
                ),
            ],
        ),
    ]
