# Generated by Django 6.0.3 on 2026-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="anonymous_user_id",
            field=models.CharField(default=45667, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="anonymous_user_id",
            field=models.CharField(max_length=255),
        ),
    ]
