# Generated by Django 6.0.3 on 2026-04-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rating_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="review_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="success",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("age_confirmation", "Age Confirmation"),
                    ("page_view", "Page View"),
                    ("search_query", "Search Query"),
                    ("filter_applied", "Filter Applied"),
                    ("filters_reset", "Filters Reset"),
                    ("cocktail_card_view", "Card View"),
                    ("cocktail_page_open", "Page Open"),
                    ("servings_changed", "Servings Changed"),
                    ("signup", "Signup"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("rating_added", "Rating Added"),
                    ("review_added", "Review Added"),
                ],
                max_length=100,
            ),
        ),
    ]
