"""
Django settings for catalogue_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-(5i^55k2-7pteu^(5hrebr)+@l4p@+gcd)&knn83ziw58=&y*e",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("true", "1")

ALLOWED_HOSTS = ["0.0.0.0", "127.0.0.1"]

if os.environ.get("ALLOWED_HOSTS"):
    try:
        ALLOWED_HOSTS += os.environ.get("ALLOWED_HOSTS").split(",")
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    except ValueError:
        print(
            "ALLOWED_HOSTS environment variable is set incorrectly, using default value"
        )

INTERNAL_IPS = ["127.0.0.1", "localhost"]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # libs
    "rest_framework",
    "debug_toolbar",
    "drf_spectacular",
    "corsheaders",
    "storages",
    # apps
    "user",
]

APPS_WITH_ANALYTICS = ["cocktail", "analytics"]
INSTALLED_APPS += APPS_WITH_ANALYTICS

AUTH_USER_MODEL = "user.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "analytics.middleware.AnonymousUserCookieMiddleware",
]

ROOT_URLCONF = "catalogue_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "catalogue_system.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    load_dotenv()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
        }
    }
    if os.environ.get("POSTGRES_SSLMODE", "disabled").lower() in (
        "require",
        "1",
        "true",
    ):
        DATABASES["default"].update(
            {
                "OPTIONS": {
                    "sslmode": "require",
                    "channel_binding": "require",
                },
            }
        )

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False

# External libs settings

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
if not CELERY_BROKER_URL:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "user.authentication.JWTHeaderFromCookieAuthentication",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Cocktail Catalogue API",
    "DESCRIPTION": "Search for your favorite cocktail recipies",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "defaultModelRendering": "model",
        "defaultModelsExpandDepth": 2,
        "defaultModelExpandDepth": 2,
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

if CELERY_BROKER_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CELERY_BROKER_URL],
            },
        },
    }
else:
    CHANNELS_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
if DEBUG:
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "vol/media/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    STATIC_ROOT = BASE_DIR / "staticfiles"

AWS_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL")
AWS_S3_CUSTOM_DOMAIN = os.environ.get("R2_CUSTOM_DOMAIN")
AWS_S3_REGION_NAME = "auto"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

ANALYTICS_DATASET_ID = os.environ.get("ANALYTICS_DATASET_ID")

if ANALYTICS_DATASET_ID and os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    CELERY_BEAT_SCHEDULE = {
        "migrate-analytics-data-to-bigquery-daily": {
            "task": "analytics.tasks.migrate_data_to_bigquery",
            "schedule": crontab(hour=8, minute=0),
        }
    }
else:
    print(
        "No ANALYTICS_DATASET_ID and/or GOOGLE_APPLICATION_CREDENTIALS, "
        "Celery_beat will not send analytics data to BigQuery."
    )

# Email
load_dotenv()
PASSWORD_RESET_TIMEOUT = 86400
EMAIL_VERIFY_RESET_TIMEOUT = 86400
DAILY_MAIL_THRESHOLD = 20
AUTO_VERIFY_EMAIL = os.environ.get(
    "AUTO_VERIFY_EMAIL", str(DEBUG)
).lower() in ("1", "true")
EMAIL_API_BASE_URL = os.environ.get("EMAIL_API_BASE_URL")
EMAIL_API_KEY = os.environ.get("EMAIL_API_KEY")
EMAIL_DOMAIN = os.environ.get("EMAIL_DOMAIN")
FRONTEND_BASE_URL = os.environ.get(
    "FRONTEND_BASE_URL", "http://127.0.0.1:5173"
)
