# Generated by Django 6.0.3 on 2026-03-25 16:21

import cocktail.models
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models, transaction


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cocktail.migrations.0002_alter_ingredient_options_and_more_squashed

def copy_similar_cocktails(apps, schema_editor):
    Cocktail = apps.get_model("cocktail", "Cocktail")
    ThroughOld = Cocktail.similar_cocktails_old.through
    Through = apps.get_model("cocktail", "SimilarCocktails")
    with transaction.atomic():
        for obj in ThroughOld.objects.all():
            Through.objects.create(
                from_cocktail_id=obj.from_cocktail_id,
                to_cocktail_id=obj.to_cocktail_id
            )


class Migration(migrations.Migration):


    replaces = []

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('alcohol', 'Alcohol'), ('mixer', 'Mixer'), ('garnish', 'Garnish')], max_length=60)),
                ('unit', models.CharField(choices=[('ml', 'Ml'), ('gram', 'Gram'), ('piece', 'Piece')], max_length=60)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alcohol_level', models.CharField(choices=[('non_alcoholic', 'Non-alcoholic'), ('low', 'Low'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=60)),
                ('sweetness_level', models.CharField(choices=[('dry', 'Dry'), ('medium', 'Medium'), ('sweet', 'Sweet')], max_length=60)),
                ('preparation', models.TextField(blank=True)),
                ('preparation_time', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cocktail.models.create_cocktail_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similar_cocktails', models.ManyToManyField(blank=True, to='cocktail.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_ingredients', to='cocktail.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_cocktails', to='cocktail.ingredient')),
            ],
            options={
                'unique_together': {('cocktail', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='cocktails', through='cocktail.CocktailIngredients', to='cocktail.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='vibes',
            field=models.ManyToManyField(blank=True, related_name='cocktails', to='cocktail.vibe'),
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='similar_cocktails',
            new_name='similar_cocktails_old',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='alcohol_level',
            field=models.CharField(choices=[('non-alcoholic', 'Non Alcoholic'), ('low', 'Low'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=60),
        ),
        migrations.CreateModel(
            name='SimilarCocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_cocktails_from', to='cocktail.cocktail')),
                ('to_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_cocktails_to', to='cocktail.cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='similar_cocktails',
            field=models.ManyToManyField(blank=True, through='cocktail.SimilarCocktails', to='cocktail.cocktail'),
        ),
        migrations.AddConstraint(
            model_name='similarcocktails',
            constraint=models.CheckConstraint(condition=models.Q(('from_cocktail', models.F('to_cocktail')), _negated=True), name='prevent_self_similarity'),
        ),
        migrations.AlterUniqueTogether(
            name='similarcocktails',
            unique_together={('from_cocktail', 'to_cocktail')},
        ),
        migrations.RunPython(
            code=copy_similar_cocktails,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='similar_cocktails_old',
        ),
        migrations.RemoveConstraint(
            model_name='similarcocktails',
            name='prevent_self_similarity',
        ),
        migrations.AddField(
            model_name='cocktailingredients',
            name='alternative_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='through_cocktails_alternative', to='cocktail.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktailingredients',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='cocktails', through='cocktail.CocktailIngredients', through_fields=('cocktail', 'ingredient'), to='cocktail.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredients',
            constraint=models.CheckConstraint(condition=models.Q(('ingredient', models.F('alternative_ingredient')), _negated=True), name='prevent_ingredient_&_alt_similarity'),
        ),
        migrations.AddConstraint(
            model_name='similarcocktails',
            constraint=models.CheckConstraint(condition=models.Q(('from_cocktail', models.F('to_cocktail')), _negated=True), name='prevent_self_cocktail_similarity'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='alcohol_promille',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='alcohol_scale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='sweetness_scale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='alcohol_level',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='sweetness_level',
        ),
    ]
