# Generated by Django 6.0.3 on 2026-03-11 17:19

import cocktail.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alcohol", "Alcohol"),
                            ("mixer", "Mixer"),
                            ("garnish", "Garnish"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "Ml"), ("gram", "Gram"), ("piece", "Piece")],
                        max_length=60,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vibe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "alcohol_level",
                    models.CharField(
                        choices=[
                            ("non_alcoholic", "Non-alcoholic"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("strong", "Strong"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "sweetness_level",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("medium", "Medium"),
                            ("sweet", "Sweet"),
                        ],
                        max_length=60,
                    ),
                ),
                ("preparation", models.TextField(blank=True)),
                ("preparation_time", models.PositiveIntegerField(default=5)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cocktail.models.create_cocktail_image_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "similar_cocktails",
                    models.ManyToManyField(blank=True, to="cocktail.cocktail"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CocktailIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_ingredients",
                        to="cocktail.cocktail",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_cocktails",
                        to="cocktail.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("cocktail", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="cocktails",
                through="cocktail.CocktailIngredients",
                to="cocktail.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="cocktail",
            name="vibes",
            field=models.ManyToManyField(
                blank=True, related_name="cocktails", to="cocktail.vibe"
            ),
        ),
    ]
