# Generated by Django 6.0.3 on 2026-03-27 21:07

import cocktail.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "average_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=3),
                ),
                ("alcohol_promille", models.PositiveIntegerField(default=0)),
                (
                    "alcohol_scale",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "sweetness_scale",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("preparation", models.TextField(blank=True)),
                ("preparation_time", models.PositiveIntegerField(default=5)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cocktail.models.create_cocktail_image_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alcohol", "Alcohol"),
                            ("mixer", "Mixer"),
                            ("garnish", "Garnish"),
                            ("glass", "Glass"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "Ml"), ("gram", "Gram"), ("piece", "Piece")],
                        max_length=60,
                    ),
                ),
            ],
            options={
                "ordering": ("category",),
            },
        ),
        migrations.CreateModel(
            name="Vibe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CocktailIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("optional", models.BooleanField(default=False)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_ingredients",
                        to="cocktail.cocktail",
                    ),
                ),
                (
                    "alternative_ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_cocktails_alternative",
                        to="cocktail.ingredient",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_cocktails",
                        to="cocktail.ingredient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="cocktails",
                through="cocktail.CocktailIngredients",
                through_fields=("cocktail", "ingredient"),
                to="cocktail.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="SimilarCocktails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_cocktails_from",
                        to="cocktail.cocktail",
                    ),
                ),
                (
                    "to_cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_cocktails_to",
                        to="cocktail.cocktail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cocktail",
            name="similar_cocktails",
            field=models.ManyToManyField(
                blank=True, through="cocktail.SimilarCocktails", to="cocktail.cocktail"
            ),
        ),
        migrations.AddField(
            model_name="cocktail",
            name="vibes",
            field=models.ManyToManyField(
                blank=True, related_name="cocktails", to="cocktail.vibe"
            ),
        ),
        migrations.AddConstraint(
            model_name="cocktailingredients",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ingredient", models.F("alternative_ingredient")), _negated=True
                ),
                name="prevent_ingredient_&_alt_similarity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cocktailingredients",
            unique_together={("cocktail", "ingredient")},
        ),
        migrations.AddConstraint(
            model_name="similarcocktails",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_cocktail", models.F("to_cocktail")), _negated=True
                ),
                name="prevent_self_cocktail_similarity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="similarcocktails",
            unique_together={("from_cocktail", "to_cocktail")},
        ),
    ]
