# Generated by Django 6.0.3 on 2026-03-13 18:52

import django.db.models.deletion
from django.db import migrations, models, transaction


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cocktail.migrations.0004_auto_20260313_1821


def copy_similar_cocktails(apps, schema_editor):
    Cocktail = apps.get_model("cocktail", "Cocktail")
    ThroughOld = Cocktail.similar_cocktails_old.through
    Through = apps.get_model("cocktail", "SimilarCocktails")
    with transaction.atomic():
        for obj in ThroughOld.objects.all():
            Through.objects.create(
                from_cocktail_id=obj.from_cocktail_id,
                to_cocktail_id=obj.to_cocktail_id
            )


class Migration(migrations.Migration):

    replaces = [('cocktail', '0002_alter_ingredient_options_and_more'), ('cocktail', '0003_similarcocktails_cocktail_similar_cocktails_and_more'), ('cocktail', '0004_auto_20260313_1821'), ('cocktail', '0005_remove_cocktail_similar_cocktails_old')]

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('category',)},
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='similar_cocktails',
            new_name='similar_cocktails_old',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='alcohol_level',
            field=models.CharField(choices=[('non-alcoholic', 'Non Alcoholic'), ('low', 'Low'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=60),
        ),
        migrations.CreateModel(
            name='SimilarCocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_cocktails_from', to='cocktail.cocktail')),
                ('to_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_cocktails_to', to='cocktail.cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='similar_cocktails',
            field=models.ManyToManyField(blank=True, through='cocktail.SimilarCocktails', to='cocktail.cocktail'),
        ),
        migrations.AddConstraint(
            model_name='similarcocktails',
            constraint=models.CheckConstraint(condition=models.Q(('from_cocktail', models.F('to_cocktail')), _negated=True), name='prevent_self_similarity'),
        ),
        migrations.AlterUniqueTogether(
            name='similarcocktails',
            unique_together={('from_cocktail', 'to_cocktail')},
        ),
        migrations.RunPython(
            copy_similar_cocktails, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='similar_cocktails_old',
        ),
    ]
