# Generated by Django 6.0.3 on 2026-03-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0002_alter_ingredient_options_and_more_squashed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="similarcocktails",
            name="prevent_self_similarity",
        ),
        migrations.AddField(
            model_name="cocktailingredients",
            name="alternative_ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="through_cocktails_alternative",
                to="cocktail.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="cocktailingredients",
            name="optional",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="cocktails",
                through="cocktail.CocktailIngredients",
                through_fields=("cocktail", "ingredient"),
                to="cocktail.ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="cocktailingredients",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ingredient", models.F("alternative_ingredient")), _negated=True
                ),
                name="prevent_ingredient_&_alt_similarity",
            ),
        ),
        migrations.AddConstraint(
            model_name="similarcocktails",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_cocktail", models.F("to_cocktail")), _negated=True
                ),
                name="prevent_self_cocktail_similarity",
            ),
        ),
    ]
