# Generated by Django 6.0.3 on 2026-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0003_remove_similarcocktails_prevent_self_similarity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="alcohol_promille",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
