# Generated by Django 6.0.3 on 2026-03-24 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0004_cocktail_alcohol_promille"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="alcohol_scale",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cocktail",
            name="sweetness_scale",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
