# Generated by Django 6.0.3 on 2026-03-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0005_cocktail_alcohol_scale_cocktail_sweetness_scale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="alcohol_level",
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="sweetness_level",
        ),
    ]
